### ISSUE TITLE
Map Placement

### ISSUE THREAD

**Issue by BZFENDSKY** [TheGiraffe3/Jibauni#1]
@TheGiraffe3 on Discord [here](https://discord.com/channels/251118043411775489/266345072554016768/1188335144734564444) there is a map for species that are trying to get in the game. The Jibauni will be overlapping with one of them, named the Naltok. 

![vanillascope2024](https://github.com/TheGiraffe3/Jibauni/assets/172621837/de0b3597-0952-4b1e-98b8-405a0f66e1b5)
I'll copy what was said, here:
This is a map of known species, as of 2024, being actively worked on with the *intent * of making it into vanilla, in no particular order. The list of creators responsible for the content, as well as links to their content, are as follows:
 * **Incipias**- RisingLeaf https://github.com/endless-sky/endless-sky/pull/8949
* **Avgi**- Azure3141 https://github.com/endless-sky/endless-sky/pull/9172
* **Xapleaux**- MasterOfGrey https://github.com/endless-sky/endless-sky/pull/6439
* **Successors**- Daeridanii1 https://discord.com/channels/251118043411775489/908108805513052220/1105241647484244098
* **Naltok**- Quantumshark https://github.com/endless-sky/endless-sky/discussions/8737
* **Mata**- Deleted User https://discord.com/channels/251118043411775489/908108805513052220/936794880770990151
* **Bashkmul**- roadrunner56 https://github.com/endless-sky/endless-sky/discussions/7983
* **Watchers**- Amazinite 

Not on the map, but still going for vanilla:
* **Searchers** - mOctave https://discord.com/channels/251118043411775489/908108805513052220/1129102382161203251

**Red Areas** denote areas that are off-limits for lore or other reasons.

**Important Note:** This includes species specifically going for vanilla. This does not include species in plug-ins that are not specifically going for vanilla, but that does not mean those species cannot be considered/won't be going for it someday. Planned vanilla systems may conflict with plug-ins.

All content on this map is not final and subject to change based on feedback in PR review or by the respective creators. Map positions are not final - if it's not in vanilla, it's not a taken spot. However, be respective to content creators if they are working on a given territory and converse with them if you're unsure.

*This is a map of content being worked on as of the beginning of 2024. It is not a map of species planned for the year 2024.*

**Comment by Quantumshark** [comment]
As the author of the Naltok, I can say that this won't be an issue. That map is outdated, the Naltok have been moved here:
![image](https://github.com/TheGiraffe3/Jibauni/assets/18634983/cd2ef26e-44a4-413d-b40b-493cbd1c930c)

**Comment by BZFENDSKY** [comment]
Apparently the map was outdated. Sorry for pinging you without reason.

**Comment by Quantumshark** [comment]
It's alright, this has served as a reminder that I need to update the discussion post.
